### PR TITLE
7.1, Api11, and additional crash protection

### PR DESCRIPTION
**Pull request by Phenrei**
ChatManager sig borrowed from QolBar; updated GameEventManager sig found myself (seems to be working despite two matches). Food refresh may be broken (but was before for me, it would always click off and re-do the same food buff anyway).  Existing favorites may have been broken by 7.1 changes to sheets.

Also includes a merge in from the previous build I'd been working on before 7.1 as I had the ExitCrafting crash again in 7.1 from the first compile. This includes alternate handling in ExitCrafting to use the macro if currently crafting, the RecipeNote.Close function if the UI is just open but not crafting, and not try anything if the UI isn't open, plus two new functions to support this change. This seems to be more stable than the old behavior.

### CODE REVIEW

**Comment by Phenrei** [comment]
Had another ExitCrafting related crash from this build (after doing a 1x craft and finishing list), but it may have been interference from another plugin messing with macros though looking at the crash stack. Had no issues after doing a longer craft and it finishing, either.

**Comment by Junie-774** [comment]
this is really awesome! I had all but given up on trying to fix the crashed; This is really helpful ^^. Thanks a lot

**Comment by Junie-774** [comment]
if food and/or favorites are broken, i'll fix it when i get a chance

**Comment by Phenrei** [comment]
Favorites work, the tables I think were just changed a little so any existing ones in people's configs may show up wrong.

**Pull request merged**
